# Generated by Django 3.2.7 on 2021-10-04 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_phone', models.IntegerField(null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product', models.CharField(max_length=100, null=True)),
                ('order_amount', models.CharField(max_length=25, null=True)),
                ('order_order_id', models.CharField(max_length=100, null=True)),
                ('order_pay_id', models.CharField(max_length=100, null=True)),
                ('order_signature', models.CharField(max_length=100, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('WEEKLY', 'WEEKLY')], default='MONTHLY', max_length=10)),
                ('plan_createdon', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(null=True)),
                ('plan_rate', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.order')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.employee')),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='sb_pln_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.subscriptionplan'),
        ),
    ]
