# Generated by Django 3.2.7 on 2021-09-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('WEEKLY', 'WEEKLY')], default='MONTHLY', max_length=10)),
                ('plan_createdon', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('plan_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
    ]
