# Generated by Django 3.2.7 on 2021-09-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_alter_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.employee'),
        ),
    ]
