# Generated by Django 3.2.7 on 2021-09-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0004_subscriptionplan_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product', models.CharField(max_length=100, null=True)),
                ('order_amount', models.CharField(max_length=25, null=True)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('sb_pln_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp.subscriptionplan')),
            ],
        ),
    ]
