# Generated by Django 3.2.7 on 2021-09-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sb_pln_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Emp.subscriptionplan'),
        ),
    ]
