# Generated by Django 3.2.7 on 2021-09-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0006_alter_order_sb_pln_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
