# Generated by Django 3.2.7 on 2021-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0007_order_order_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pay_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
