# Generated by Django 3.2.7 on 2021-09-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0008_auto_20210919_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table=None,
        ),
    ]
