# Generated by Django 3.2.7 on 2021-09-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0009_auto_20210919_1328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription_plan',
        ),
    ]
