# Generated by Django 3.2.7 on 2021-09-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_token_user'),
        ('admin', '0004_alter_logentry_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Emp', '0011_subscriptionplan_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginUser',
            new_name='login_user',
        ),
    ]
