# Generated by Django 3.2.7 on 2021-09-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_token_user'),
        ('admin', '0004_alter_logentry_user'),
        ('Emp', '0012_rename_loginuser_login_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_user',
            new_name='loginUser',
        ),
    ]
